  // Build Json for prop
  const prop = '{ "prop" : [' +
  '{"num": "07","full_case": "Do you agree that the electricity output of thermal power plants should be lowered by \\"at least 1 percent per year on average\\"?" , "Reasoning": "1. Many recent studies have shown that PM 2.5 is closely related to adverse health outcomes, especially for the elderly and children. <br><br> 2. Air pollution in Taiwan has been exacerbated by President Tsai\'s \\"2025 Nuclear-free Homeland\\" policy. If the plan proceeds, 80% of the electricity output in Taiwan will be generated by thermal power plants by 2025, which will put the health of all of the Taiwanese people under threat. <br><br> 3. President Tsai is sacrificing the health of the residents in central and southern Taiwan to her nuclear-free energy policy since most of the thermal power plants are located in those areas.", "src_map": "https://plotdb.io/v/chart/19356?q=7&lang=en", "ratio":"40.27%", "result":"Approved"},' +
  '{"num": "08","full_case": "Do you agree that Taiwan should establish an energy policy that undertakes not to construct any new coal-fired power plants or generators or expand existing facilities (including the expansion of the Shen-ao Power Plant)?","Reasoning": "The current coal-fired electricity output in Taiwan has already met the government\'s target in the \\"2025 Nuclear-free Homeland\\" plan. The Shen\'ao Power Plant expansion project is therefore unnecessary and should be abandoned.", "src_map": "https://plotdb.io/v/chart/19356?q=8&lang=en", "ratio":"38.46%", "result": "Approved"},' +
  '{"num": "09","full_case": "Do you agree the government should maintain the ban on imports of agricultural products and food from areas in Japan affected by the Fukushima Daiichi nuclear plant disaster on March 11, 2011, including Fukushima, Ibaraki, Gunma, Tochigi and Chiba prefectures?","Reasoning": "The government is planning on easing the food import ban introduced following the Fukushima Daiichi nuclear plant crisis. However, this ban should not be lifted because of the following reasons: <br><br> 1. In one of the hearings, the Institute of Nuclear Energy Research in Taiwan mentioned there are only 10 part-time employees in charge of the food examination process. If the import ban is lifted, they will need to expand the budget to hire more examiners. <br><br> 2. Due to the geographical proximity and the food taste of the Taiwanese people, the Taiwan-Japan trade relationship has been strong over decades. Taiwan therefore has a higher probability of being exposed to nuclear-contaminated products. <br><br> 3. Whether or not to relax the Japanese food import ban is a highlight in the negotiation of signing the Economic Partnership Agreement with Japan. It will be a great loss for Taiwan to abandon this valuable bargaining chip even before the negotiation of the Economic Partnership Agreement starts. <br><br> 4. The action of lifting the Japanese food import ban contradicts the government\'s \\"2025 Nuclear-free Homeland\\" policy. To prevent citizens from being exposed to nuclear-contaminated products, the nation should continue banning food imports from the areas that were affected from the Fukushima Daiichi nuclear plant crisis.", "src_map": "https://plotdb.io/v/chart/19356?q=9&lang=en", "ratio":"39.44%", "result":"Approved"},' +
  '{"num": "10","full_case": "Do you agree that marriage defined in the Civil Code should be restricted to the union between one man and one woman?","Reasoning": "1. The current Civil Code has not specified whether a marriage could only be formed by a man and a woman. <br><br> 2. This proposal is not against the Judicial Yuan Interpretation No. 748 which the Supreme Court ruled that the prohibition of same-sex marriage violates the Constitution. <br><br> 3. The current Civil Code should restrict marriage to be formed by a man and a woman in order to maintain the stability of law. Same-sex marriage should be regulated by other special laws that have yet to be established. <br><br> 4. The Constitution of the Republic of China enshrines the legislative initiative right of the people. Hence, the definition of a marriage in the Civil Code should be decided by the people through referendum. <br><br>", "src_map": "https://plotdb.io/v/chart/19356?q=10&lang=en", "ratio":"38.76%", "result":"Approved"},' +
  '{"num": "11","full_case": "Do you agree that the Ministry of Education and individual schools should not cover LGBT materials in gender education in elementary and middle schools, as detailed in the Enforcement Rules for the Gender Equity Education Act?","Reasoning": "1. It is inappropriate to cover LGBT materials in gender education in elementary and middle schools. <br><br> 2. The Ministry of Education should abolish Article 13 in the Gender Equity Education Act, which states that LGBT education should be covered in gender education. <br><br> 3. This proposal is not against gender equity. It is to prevent children and teenagers from being sexually confused, which is likely to happen if they are exposed to LGBT information at a young age. <br><br> 4. The Constitution of the Republic of China enshrines the legislative initiative right of the people. Hence, what to be included in gender education should be decided by the people through referendum. <br><br> ", "src_map": "https://plotdb.io/v/chart/19356?q=11&lang=en", "ratio":"35.85%", "result":"Approved"},' +
  '{"num": "12","full_case": "Do you agree that the right of same-sex couples living together permanently should be regulated under other special laws that are independent from the Civil Code?","Reasoning": "1. According to the Judicial Yuan Interpretation No. 748 from the Supreme Court, the prohibition of same-sex marriage violates the Constitution and the Legislative Yuan has two years to amend the marriage law. This means that it is possible to establish a special law that is independent from the Civil Code to enshrine same-sex couples the right of getting married. <br><br>  2. There are numerous differences between a heterosexual marriage and a homosexual marriage. For example, same-sex couple is not able to have kids naturally. SInce the Current Code is designed for heterosexual marriage, it would be the best for the same-sex couples to have their own law.", "src_map": "https://plotdb.io/v/chart/19356?q=12&lang=en", "ratio":"32.40%", "result":"Approved"},' +
  '{"num": "13","full_case": "Do you agree that Taiwan should use the name \\"Taiwan\\" to apply for participating in all international sporting events, including the 2020 Summer Olympics in Tokyo?","Reasoning": "1. According to Article 30 of the Olympic Charter, the name of an NOC (National Olympic Committees) must reflect the territorial extent and tradition of its country and shall be subject to the approval of the IOC (International Olympic Committee) Executive Board. However, the current name \\"Chinese Taipei\\" reflects neither the territorial extent nor the tradition of Taiwan since many of the athletes are not from Taipei. <br><br> 2. Changing names to participate in the Olympics is not something that has never happened in the history. Taiwan has used \\"Formosa\\" in 1956 and \\"Taiwan\\" in 1960, 1964, and 1968, to participate in the Olympics before. Moreover, this has also happened to other countries before. For example, in 1992, Holland changed its name to “Netherlands” in the Olympics. <br><br> 3. Changing our name from “Chinese Taipei” to “Taiwan” will not affect the right of our athletes to participate in the Olympics. In 2016, the Brazilian NOC was suspended by the IOC because of corruption. However, during that period of time, the IOC guaranteed the right of the Brazilian athletes to compete in the games. This implies that the Chinese Taipei NOC and our athletes are two independent things that are separable. <br><br> ", "src_map": "https://plotdb.io/v/chart/19356?q=13&lang=en", "ratio":"24.11%", "result":"Rejected"},' +
  '{"num": "14","full_case": "Do you agree that the right of same-sex couples getting married should be regulated under the Civil Code?","Reasoning": "1. According to the  Judicial Yuan Interpretation No. 748 from the Supreme Court, the current Civil Code lacks an explicit specification on enshrining same-sex couples the right of getting married, which violates the Constitution. <br><br> 2. The idea of prohibiting same-sex couples from using their rights following the Civil Code but a different special law is an embodiment of discrimination. Not only would this idea worsen the discrimination same-sex couples face, it would also create unnecessary social costs.  <br><br> 3. According to Article 9 in the Referendum Act, \\"a proposal shall be raised for one matter only\\". The effect this proposal aims to achieve is not exactly the same matter that the 10th and 12th cases in the referendum aim at. If case 10 and 12 are not passed, it means that a marriage should not be restricted to be formed by a man and a woman and the right of same-sex couples living together permanently should be regulated under a different law that is not the Civil Code. However, there are multiple ways of interpreting \\"a marriage should not be restricted to be formed by a man and a woman\\". It could mean that a marriage could be formed by more than a man and more than a woman. Likewise, \\"the right of same-sex couples living together permanently should be regulated under a different law that is not the Civil Code\\" is ambiguous since living together permanently is not equivalent to a marriage relationship. Hence, the effects case 10 and 12 are trying to achieve are equivocal and are not on the exact opposite side of the matter of our proposal is targeting at.", "src_map": "https://plotdb.io/v/chart/19356?q=14&lang=en", "ratio":"17.12%", "result":"Rejected"},' +
  '{"num": "15","full_case": "Do you agree that the gender equity education taught at all stages of the national curriculum stipulated in the Gender Equity Education Act should cover emotional, sex, and LGBT education?","Reasoning": "1. Covering emotional, sex, and LGBT education in the curriculum in schools prevents bullying from happening. <br><br>  2. The current regulation on emotional, sex and LGBT education is only a delegated legislation. However, it should be futher enhanced to a primary-legistlative level.", "src_map": "https://plotdb.io/v/chart/19356?q=15&lang=en", "ratio":"17.75%", "result":"Rejected"},' +
  '{"num": "16","full_case": "Do you agree to abolish Section 1 of Article 95 of the Electricity Act, which states that \\"all nuclear power generating facilities shall cease operations by 2025\\"?","Reasoning": "1. Phasing out nuclear power plants unconditionally will cause serious air pollution and damage to the environment. <br><br> 2. The cost of using thermal power plants as the main source to meet our demand of electricity varies a lot due to the fluctuating international price of the fossil fuel. Japan has switched back to using nuclear power after suffering from a serious trade deficit for consecutive years. <br><br> 3. Nuclear phase-out will not only increase our carbon emissions, but also decrease the capacity of electricity power we could generate, which falls short of our need of electricity power. <br><br> ", "src_map": "https://plotdb.io/v/chart/19356?q=16&lang=en", "ratio": "29.84%", "result": "Approved"}]}';
  
  const prop_obj = JSON.parse(prop);

  function prop_func(x) {
  // Add active class to the current button (highlight it)
  const prop_btn = document.getElementById("nav-rfrd");
  const prop_lis = prop_btn.getElementsByClassName("nav-rfrd-link");
  for (var i = 0; i < prop_lis.length; i++) {
    prop_lis[i].addEventListener("click", function() {
      var current = prop_btn.getElementsByClassName("StepActive");
      current[0].className = current[0].className.replace(" StepActive", "");
      this.className += " StepActive";
    });
  }
  // Replace by Case
  let prop_num = prop_obj.prop[x].num;
  document.getElementById("prop_num").innerHTML = prop_num;
  document.getElementById("i_prop_num").innerHTML = prop_num;
  let full_case = prop_obj.prop[x].full_case;
  document.getElementById("full_case").innerHTML = full_case;
  document.getElementById("i_prop_name").innerHTML = full_case;
  let reasoning = prop_obj.prop[x].Reasoning;
  document.getElementById("reasoning").innerHTML = reasoning;
  let src_map = prop_obj.prop[x].src_map;
  document.getElementById('mapIframe').src = src_map;
  let ratio = prop_obj.prop[x].ratio;
  document.getElementById("pie_ratio").innerHTML = ratio;
  let result = prop_obj.prop[x].result;
  document.getElementById("pie_result").innerHTML = result;


  // further reading

  const proposal = {
    vote0: [
    {'title': 'Taiwan voters pass three energy-related referenda', 'url':'https://en.rti.org.tw/news/view/id/2000164'}
    ],
    vote1: [
    {'title': 'KMT unveils Shenao Power Plant referendum drive', 'url':'http://www.taipeitimes.com/News/taiwan/archives/2018/04/14/2003691292'},
    {'title': 'Taiwan Takes a Step Back With New Coal Plant', 'url':'https://thediplomat.com/2018/05/taiwan-takes-a-step-back-with-new-coal-plant/'}
    ],
    vote2: [
    {'title': 'Taiwan to vote on whether to maintain ban of some Japanese food products in referendum next month', 'url':'https://www.japantimes.co.jp/news/2018/10/09/national/taiwan-vote-whether-maintain-ban-japanese-food-products-referendum-next-month/#.W_sGBC2ZM1I'},
    {'title': 'Taiwan votes to maintain ban on food from Fukushima disaster areas', 'url':'https://asia.nikkei.com/Politics/International-Relations/Taiwan-votes-to-maintain-ban-on-food-from-Fukushima-disaster-areas/'}
    ],
    vote3: [
    {'title': 'Taiwan was supposed to be the first place in Asia to legalize gay marriage. Then things got complicated.', 'url':'https://www.washingtonpost.com/world/2018/11/23/taiwan-was-supposed-be-first-asian-country-legalize-gay-marriage-then-things-got-complicated/?utm_term=.61f6a2376a27'},
    {'title': 'Taiwan voters reject same-sex marriage', 'url':'https://www.cnn.com/2018/11/25/asia/taiwan-same-sex-marriage-referendum/index.html'}
    ],
    vote4: [
    {'title': 'Uncertainty grips gay people in Taiwan as same-sex marriage goes to the vote', 'url':'https://www.theguardian.com/global-development/2018/nov/24/taiwan-same-sex-marriage-vote-referendum'},
    ],
    vote5: [
    {'title': 'Taiwan’s image as Asia’s LGBT rights beacon takes a hit as same-sex marriage referendum fails', 'url':'https://www.scmp.com/news/china/politics/article/2174881/taiwans-image-asias-lgbt-rights-beacon-takes-hit-same-sex'},
    {'title': 'Same-sex marriage referendums: Taiwan Civil Code may remain unchanged', 'url':'https://www.taiwannews.com.tw/en/news/3582617'},
    {'title': '"A great divide": Inside the battle to stop same-sex marriage in Taiwan', 'url':'https://news.google.com/articles/CAIiEBv4vfa8MUh0cvY-A0uqfp0qGQgEKhAIACoHCAowocv1CjCSptoCMPrTpgU?hl=en-US&gl=US&ceid=US%3Aen'}
    ],
    vote6: [
    {'title': 'Olympic referendum: Shall it be "Taiwan" or "Chinese Taipei"', 'url':'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=8&cad=rja&uact=8&ved=2ahUKEwicgPWItPDeAhXm44MKHcrhC68QFjAHegQIBRAB&url=https%3A%2F%2Fwww.washingtonpost.com%2Fsports%2Folympics%2Folympic-referendum-shall-it-be-taiwan-or-chinese-taipei%2F2018%2F11%2F22%2F2b84b5aa-ee17-11e8-8b47-bd0975fd6199_story.html&usg=AOvVaw2YJIhbevX-pYwvvmrqmqBP'},
    {'title': 'Taiwan to vote on changing "Chinese Taipei" Olympic name', 'url':'https://www.cnn.com/2018/11/23/asia/taiwan-referendum-olympic-chinese-taipei-intl/index.html'}
    ],
    vote7: [
    {'title': 'Taiwan Votes Against Same-Sex Marriage in Referendum', 'url':'http://time.com/5462767/taiwan-same-sex-marriage-referendum/'},
    {'title': 'Same-sex marriage advocates lose Taiwan referendums', 'url':'https://www.aljazeera.com/news/2018/11/sex-marriage-advocates-lose-taiwan-referendums-181124171649837.html'},
    {'title': 'Taiwan Voters Reject Legalizing Same-Sex Marriage in Referendum', 'url':'https://www.huffingtonpost.com/entry/taiwan-votes-against-same-sex-marriage_us_5bfac861e4b0771fb6b9daf2'},
    ],
    vote8: [
    {'title': 'Sex, lies and heated debate: Taiwan prepares to vote in gay marriage referendum', 'url':'https://www.theguardian.com/world/2018/nov/22/taiwan-gay-marriage-referendum-vote'},
    ],
    vote9: [
    {'title': '"Go nuclear to go green" irrational', 'url':'http://www.taipeitimes.com/News/editorials/archives/2018/09/19/2003700694'},
    {'title': 'Taiwan Power Co. respects referendum results but will follow government policy', 'url':'https://www.taiwannews.com.tw/en/news/3583184'},
    {'title': 'Pro-Nuclear Activists Win Landslide Electoral Victory In Taiwan', 'url':'https://www.forbes.com/sites/michaelshellenberger/2018/11/24/pro-nuclear-activists-win-landslide-electoral-victory-in-taiwan/#16aec9b329a0'},
    ],
  };

  
  function makeUL(data) {

    var prevList = document.getElementById('readingList');
    if (prevList) {
    prevList.remove(); // Removes the div with the 'readings' id
  }

    // Create the list element:
    var list = document.createElement('ul');
    list.setAttribute('id', 'readingList');

    data["vote"+x].forEach(function(d) {

    // Create the list item:
    var item = document.createElement('li');

    // Set its contents:

    var tmp = document.createElement('a');
    var tmpText = document.createTextNode(d.title);
    tmp.setAttribute('href', d.url);
    tmp.appendChild(tmpText);
    item.appendChild(tmp);
    list.appendChild(item);
  })

    // Finally, return the constructed list:
    return list;
  }

  let returnList = makeUL(proposal);

  // Add the List to #reading:
  document.getElementById('reading').appendChild(returnList);



  document.querySelector('#viz').scrollIntoView({ 
    behavior: 'smooth' 
  });

}



